import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by dashboard",
}

export default function DashboardLayout({
    children
}: {
    children: React.ReactNode
}) {
    return <>
        <div>
            from dashboard
            {children}
        </div>
    </>
}